### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by dimovskidamjan** [infinum/Halley#14]
I noticed there is a typo in a protocol declaration: `IncludeableType` is grammatically incorrect, it should be `IncludableType`. This would be a breaking change for all uses of Halley where this protocol is used or extended so it needs to be handled carefully and the change needs to be documented.

**Comment by fgulan** [comment]
Fixed in 1.5.0 version with [available and renamed](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/attributes/#available) attribute so Xcode will autocomplete with possible fix.
